repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241
    hooks:
      - id: ruff
        args: [
          "--fix",  # Corrige automaticamente os problemas de linting
          "--line-length=100",  # Config do comprimento de linha
          "--ignore=E203,E231,W503,E722,E711,E701,E704",  # Ignora regras especificas (retiradas da config do flake8)
          "--per-file-ignores=*/__init__.py:F401"  # Ignorar imports não usados em __init__.py
        ]

  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: 0.3.4
    hooks:
      - id: auto-walrus  # Sugere o uso do operador Walrus (:=) onde for aplicavel

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: ['--py311-plus']  # Atualiza o código para usar as features mais recentes do Python 3.11
