[app]
loglevel="INFO"

[dropbox.models]
public_safety = "/public_safety.pt"
plate_yolo_detection = "/yolo_plate_200_ep.pt"
yolov8x = "/yolov11x.pt"
pose = "/yolov11x-pose.pt"
plate_paddle_recognition = "/best_inference_paddle"
plate_paddle_detection = "/en_PP-OCRv3_det_infer"
plate_paddle_cls = "/ch_ppocr_mobile_v2.0_cls_infer"

[paddleocr]
rec_algorithm = "SVTR_LCNet"
rec_image_shape = "3,48,320"
use_space_char = true
use_gpu = false